// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"
#include "../user_management.h"
#include "../ui_login.h"

lv_obj_t *ui_Screen2 = NULL;
lv_obj_t *ui_UserLoginSlider = NULL;
lv_obj_t *ui_BackIndex = NULL;
lv_obj_t *ui_BackIndexText = NULL;
lv_obj_t *ui_UserLogo1 = NULL;
lv_obj_t *ui_LogoImage2 = NULL;
lv_obj_t *ui_UserText2 = NULL;
lv_obj_t *ui_UserInfo2 = NULL;
lv_obj_t *ui_Info13 = NULL;
lv_obj_t *ui_Info9 = NULL;
lv_obj_t *ui_Info10 = NULL;
lv_obj_t *ui_Info11 = NULL;
lv_obj_t *ui_Image13 = NULL;
lv_obj_t *ui_Image8 = NULL;
lv_obj_t *ui_Image10 = NULL;
lv_obj_t *ui_Image11 = NULL;
lv_obj_t *ui_Image12 = NULL;
lv_obj_t *ui_UserLogin = NULL;
lv_obj_t *ui_LoginOpera = NULL;
lv_obj_t *ui_Logo2 = NULL;
lv_obj_t *ui_Lightning2 = NULL;
lv_obj_t *ui_LoginSelect = NULL;
lv_obj_t *ui_Login = NULL;
lv_obj_t *ui_Register = NULL;
lv_obj_t *ui_LoginText = NULL;
lv_obj_t *ui_RegisterText = NULL;
lv_obj_t *ui_LoginBtn = NULL;
lv_obj_t *ui_LoginBtnText = NULL;
lv_obj_t *ui_LoginArea = NULL;
lv_obj_t *ui_PhoneText1 = NULL;
lv_obj_t *ui_PhoneTx1 = NULL;
lv_obj_t *ui_PasswordText = NULL;
lv_obj_t *ui_PasswordTx = NULL;
lv_obj_t *ui_RegisterOpera = NULL;
lv_obj_t *ui_Logo6 = NULL;
lv_obj_t *ui_Lightning6 = NULL;
lv_obj_t *ui_RegisterSelect = NULL;
lv_obj_t *ui_Register1 = NULL;
lv_obj_t *ui_Login1 = NULL;
lv_obj_t *ui_LoginText1 = NULL;
lv_obj_t *ui_RegisterText1 = NULL;
lv_obj_t *ui_RegisterBtn = NULL;
lv_obj_t *ui_LoginBtnText4 = NULL;
lv_obj_t *ui_RegisterArea = NULL;
lv_obj_t *ui_PhoneText2 = NULL;
lv_obj_t *ui_PhoneTx2 = NULL;
lv_obj_t *ui_PasswordTx1 = NULL;
lv_obj_t *ui_PasswordText1 = NULL;
lv_obj_t *ui_ConfirmTx = NULL;
lv_obj_t *ui_ConfirmText = NULL;
lv_obj_t *ui_Keyboard1 = NULL;
// event funtions
void ui_event_BackIndex(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_Register(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_flag_modify(ui_RegisterOpera, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_LoginBtn(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        handle_login_attempt();
    }
}

void ui_event_PhoneTx1(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_keyboard_set_target(ui_Keyboard1, ui_PhoneTx1);
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if (event_code == LV_EVENT_DEFOCUSED)
    {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_PasswordTx(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_keyboard_set_target(ui_Keyboard1, ui_PasswordTx);
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if (event_code == LV_EVENT_DEFOCUSED)
    {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_Login1(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_flag_modify(ui_RegisterOpera, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_RegisterBtn(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        handle_register_attempt();
        // 注册成功后保持在注册界面或切换到登录界面
        // _ui_flag_modify(ui_RegisterOpera, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        // _ui_flag_modify(ui_LoginOpera, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_PhoneTx2(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_keyboard_set_target(ui_Keyboard1, ui_PhoneTx2);
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if (event_code == LV_EVENT_DEFOCUSED)
    {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_PasswordTx1(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_keyboard_set_target(ui_Keyboard1, ui_PasswordTx1);
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if (event_code == LV_EVENT_DEFOCUSED)
    {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_ConfirmTx(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_keyboard_set_target(ui_Keyboard1, ui_ConfirmTx);
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if (event_code == LV_EVENT_DEFOCUSED)
    {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

// my event
void ClearText(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        lv_textarea_set_text(ui_PhoneTx1, "");
        lv_textarea_set_text(ui_PasswordTx, "");
        lv_textarea_set_text(ui_PhoneTx2, "");
        lv_textarea_set_text(ui_PasswordTx1, "");
        lv_textarea_set_text(ui_ConfirmTx, "");
    }
}

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_UserLoginSlider = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_UserLoginSlider, 300);
    lv_obj_set_height(ui_UserLoginSlider, 480);
    lv_obj_set_align(ui_UserLoginSlider, LV_ALIGN_LEFT_MID);
    lv_obj_remove_flag(ui_UserLoginSlider, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_UserLoginSlider, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_UserLoginSlider, lv_color_hex(0x1A1A1A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_UserLoginSlider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_UserLoginSlider, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackIndex = lv_button_create(ui_UserLoginSlider);
    lv_obj_set_width(ui_BackIndex, 80);
    lv_obj_set_height(ui_BackIndex, 40);
    lv_obj_add_flag(ui_BackIndex, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_remove_flag(ui_BackIndex, LV_OBJ_FLAG_SCROLLABLE);   /// Flags
    lv_obj_set_style_bg_color(ui_BackIndex, lv_color_hex(0x00D4FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BackIndex, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_event_cb(ui_BackIndex, ClearText, LV_EVENT_ALL, NULL);

    ui_BackIndexText = lv_label_create(ui_BackIndex);
    lv_obj_set_width(ui_BackIndexText, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_BackIndexText, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_BackIndexText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BackIndexText, "Back");

    ui_UserLogo1 = lv_obj_create(ui_UserLoginSlider);
    lv_obj_remove_style_all(ui_UserLogo1);
    lv_obj_set_width(ui_UserLogo1, 50);
    lv_obj_set_height(ui_UserLogo1, 50);
    lv_obj_set_x(ui_UserLogo1, 0);
    lv_obj_set_y(ui_UserLogo1, 80);
    lv_obj_set_align(ui_UserLogo1, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_UserLogo1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_UserLogo1, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_UserLogo1, lv_color_hex(0x00D4FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_UserLogo1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LogoImage2 = lv_image_create(ui_UserLogo1);
    lv_image_set_src(ui_LogoImage2, &ui_img_user_png);
    lv_obj_set_width(ui_LogoImage2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_LogoImage2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_LogoImage2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LogoImage2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_LogoImage2, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_UserText2 = lv_label_create(ui_UserLoginSlider);
    lv_obj_set_width(ui_UserText2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_UserText2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_UserText2, 0);
    lv_obj_set_y(ui_UserText2, 150);
    lv_obj_set_align(ui_UserText2, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_UserText2, "User");
    lv_obj_set_style_text_color(ui_UserText2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_UserText2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UserInfo2 = lv_obj_create(ui_UserLoginSlider);
    lv_obj_remove_style_all(ui_UserInfo2);
    lv_obj_set_width(ui_UserInfo2, 200);
    lv_obj_set_height(ui_UserInfo2, 100);
    lv_obj_set_align(ui_UserInfo2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_UserInfo2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Info13 = lv_label_create(ui_UserInfo2);
    lv_obj_set_width(ui_Info13, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Info13, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Info13, 28);
    lv_obj_set_y(ui_Info13, 7);
    lv_label_set_text(ui_Info13, "station map");
    lv_obj_set_style_text_color(ui_Info13, lv_color_hex(0xA0A0A0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Info13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Info9 = lv_label_create(ui_UserInfo2);
    lv_obj_set_width(ui_Info9, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Info9, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Info9, 28);
    lv_obj_set_y(ui_Info9, 47);
    lv_label_set_text(ui_Info9, "Make an appointment");
    lv_obj_set_style_text_color(ui_Info9, lv_color_hex(0xA0A0A0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Info9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Info10 = lv_label_create(ui_UserInfo2);
    lv_obj_set_width(ui_Info10, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Info10, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Info10, 26);
    lv_obj_set_y(ui_Info10, 27);
    lv_label_set_text(ui_Info10, "Scan the code");
    lv_obj_set_style_text_color(ui_Info10, lv_color_hex(0xA0A0A0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Info10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Info11 = lv_label_create(ui_UserInfo2);
    lv_obj_set_width(ui_Info11, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Info11, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Info11, 28);
    lv_obj_set_y(ui_Info11, 67);
    lv_label_set_text(ui_Info11, "registration\n");
    lv_obj_set_style_text_color(ui_Info11, lv_color_hex(0xA0A0A0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Info11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image13 = lv_image_create(ui_UserInfo2);
    lv_image_set_src(ui_Image13, &ui_img_dot_png);
    lv_obj_set_width(ui_Image13, LV_SIZE_CONTENT);          /// 1
    lv_obj_set_height(ui_Image13, LV_SIZE_CONTENT);         /// 1
    lv_obj_add_flag(ui_Image13, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image13, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_image_set_scale(ui_Image13, 180);

    ui_Image8 = lv_image_create(ui_UserInfo2);
    lv_image_set_src(ui_Image8, &ui_img_dot_png);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Image8, 0);
    lv_obj_set_y(ui_Image8, 60);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_image_set_scale(ui_Image8, 180);

    ui_Image10 = lv_image_create(ui_UserInfo2);
    lv_image_set_src(ui_Image10, &ui_img_dot_png);
    lv_obj_set_width(ui_Image10, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Image10, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Image10, 0);
    lv_obj_set_y(ui_Image10, 40);
    lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image10, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_image_set_scale(ui_Image10, 180);

    ui_Image11 = lv_image_create(ui_UserInfo2);
    lv_image_set_src(ui_Image11, &ui_img_dot_png);
    lv_obj_set_width(ui_Image11, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Image11, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Image11, 0);
    lv_obj_set_y(ui_Image11, 20);
    lv_obj_add_flag(ui_Image11, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image11, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_image_set_scale(ui_Image11, 180);

    ui_Image12 = lv_image_create(ui_UserLoginSlider);
    lv_image_set_src(ui_Image12, &ui_img_model3_png);
    lv_obj_set_width(ui_Image12, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Image12, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Image12, 0);
    lv_obj_set_y(ui_Image12, -26);
    lv_obj_set_align(ui_Image12, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Image12, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image12, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_image_set_scale(ui_Image12, 300);

    ui_UserLogin = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_UserLogin, 500);
    lv_obj_set_height(ui_UserLogin, 480);
    lv_obj_set_align(ui_UserLogin, LV_ALIGN_RIGHT_MID);
    lv_obj_remove_flag(ui_UserLogin, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_UserLogin, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_UserLogin, lv_color_hex(0x0A0A0A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_UserLogin, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_UserLogin, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LoginOpera = lv_obj_create(ui_UserLogin);
    lv_obj_set_width(ui_LoginOpera, 400);
    lv_obj_set_height(ui_LoginOpera, 360);
    lv_obj_set_x(ui_LoginOpera, 0);
    lv_obj_set_y(ui_LoginOpera, 30);
    lv_obj_set_align(ui_LoginOpera, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_LoginOpera, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_LoginOpera, lv_color_hex(0x1A1A1A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LoginOpera, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_LoginOpera, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Logo2 = lv_obj_create(ui_LoginOpera);
    lv_obj_remove_style_all(ui_Logo2);
    lv_obj_set_width(ui_Logo2, 70);
    lv_obj_set_height(ui_Logo2, 70);
    lv_obj_set_align(ui_Logo2, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_Logo2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_Logo2, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Logo2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Admin2);
    ui_object_set_themeable_style_property(ui_Logo2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Admin2);
    lv_obj_set_style_bg_grad_color(ui_Logo2, lv_color_hex(0x00ECC8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Logo2, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Lightning2 = lv_image_create(ui_Logo2);
    lv_image_set_src(ui_Lightning2, &ui_img_lightning_png);
    lv_obj_set_width(ui_Lightning2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Lightning2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_Lightning2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Lightning2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Lightning2, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_LoginSelect = lv_obj_create(ui_LoginOpera);
    lv_obj_set_width(ui_LoginSelect, 300);
    lv_obj_set_height(ui_LoginSelect, 30);
    lv_obj_set_x(ui_LoginSelect, 0);
    lv_obj_set_y(ui_LoginSelect, 100);
    lv_obj_set_align(ui_LoginSelect, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_LoginSelect, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_LoginSelect, lv_color_hex(0x2A2A2A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LoginSelect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_LoginSelect, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Login = lv_obj_create(ui_LoginSelect);
    lv_obj_set_width(ui_Login, 100);
    lv_obj_set_height(ui_Login, 30);
    lv_obj_set_align(ui_Login, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Login, LV_OBJ_FLAG_EVENT_BUBBLE);  /// Flags
    lv_obj_remove_flag(ui_Login, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_Login, lv_color_hex(0x1A1A1A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Login, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Login, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Login, lv_color_hex(0x1A1A1A), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_opa(ui_Login, 255, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_color(ui_Login, lv_color_hex(0x1A1A1A), LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_bg_opa(ui_Login, 0, LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_add_event_cb(ui_Login, ClearText, LV_EVENT_ALL, NULL);

    ui_Register = lv_obj_create(ui_LoginSelect);
    lv_obj_set_width(ui_Register, 100);
    lv_obj_set_height(ui_Register, 30);
    lv_obj_set_align(ui_Register, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_Register, LV_OBJ_FLAG_EVENT_BUBBLE);                           /// Flags
    lv_obj_remove_flag(ui_Register, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_Register, lv_color_hex(0x1A1A1A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Register, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Register, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Register, lv_color_hex(0x1A1A1A), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Register, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_Register, lv_color_hex(0x1A1A1A), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_opa(ui_Register, 255, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_color(ui_Register, lv_color_hex(0x1A1A1A), LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_bg_opa(ui_Register, 0, LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_add_event_cb(ui_Register, ClearText, LV_EVENT_ALL, NULL);

    ui_LoginText = lv_label_create(ui_LoginSelect);
    lv_obj_set_width(ui_LoginText, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_LoginText, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_LoginText, 29);
    lv_obj_set_y(ui_LoginText, 0);
    lv_obj_set_align(ui_LoginText, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LoginText, "Login");
    lv_obj_set_style_text_color(ui_LoginText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LoginText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RegisterText = lv_label_create(ui_LoginSelect);
    lv_obj_set_width(ui_RegisterText, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_RegisterText, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_RegisterText, -15);
    lv_obj_set_y(ui_RegisterText, 0);
    lv_obj_set_align(ui_RegisterText, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_RegisterText, "Register");
    lv_obj_set_style_text_color(ui_RegisterText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RegisterText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LoginBtn = lv_button_create(ui_LoginOpera);
    lv_obj_set_width(ui_LoginBtn, 260);
    lv_obj_set_height(ui_LoginBtn, 35);
    lv_obj_set_x(ui_LoginBtn, 4);
    lv_obj_set_y(ui_LoginBtn, 0);
    lv_obj_set_align(ui_LoginBtn, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_LoginBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_remove_flag(ui_LoginBtn, LV_OBJ_FLAG_SCROLLABLE);   /// Flags
    lv_obj_set_style_bg_color(ui_LoginBtn, lv_color_hex(0x00D4FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LoginBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LoginBtnText = lv_label_create(ui_LoginBtn);
    lv_obj_set_width(ui_LoginBtnText, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_LoginBtnText, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_LoginBtnText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LoginBtnText, "Login");
    lv_obj_set_style_text_font(ui_LoginBtnText, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LoginArea = lv_obj_create(ui_LoginOpera);
    lv_obj_set_width(ui_LoginArea, 290);
    lv_obj_set_height(ui_LoginArea, 145);
    lv_obj_set_x(ui_LoginArea, 0);
    lv_obj_set_y(ui_LoginArea, -50);
    lv_obj_set_align(ui_LoginArea, LV_ALIGN_BOTTOM_MID);
    lv_obj_remove_flag(ui_LoginArea, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_LoginArea, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LoginArea, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_LoginArea, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PhoneText1 = lv_label_create(ui_LoginArea);
    lv_obj_set_width(ui_PhoneText1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_PhoneText1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_PhoneText1, 5);
    lv_obj_set_y(ui_PhoneText1, 0);
    lv_label_set_text(ui_PhoneText1, "Phone");
    lv_obj_set_style_text_color(ui_PhoneText1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PhoneText1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PhoneTx1 = lv_textarea_create(ui_LoginArea);
    lv_obj_set_width(ui_PhoneTx1, 260);
    lv_obj_set_height(ui_PhoneTx1, 35);
    lv_obj_set_x(ui_PhoneTx1, 0);
    lv_obj_set_y(ui_PhoneTx1, 22);
    lv_obj_remove_flag(ui_PhoneTx1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_text_color(ui_PhoneTx1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PhoneTx1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PhoneTx1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PhoneTx1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PhoneTx1, lv_color_hex(0x2A2A2A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PhoneTx1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PhoneTx1, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_PhoneTx1, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PhoneTx1, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_PasswordText = lv_label_create(ui_LoginArea);
    lv_obj_set_width(ui_PasswordText, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_PasswordText, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_PasswordText, 5);
    lv_obj_set_y(ui_PasswordText, 60);
    lv_label_set_text(ui_PasswordText, "PassWord");
    lv_obj_set_style_text_color(ui_PasswordText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PasswordText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PasswordTx = lv_textarea_create(ui_LoginArea);
    lv_obj_set_width(ui_PasswordTx, 260);
    lv_obj_set_height(ui_PasswordTx, 35);
    lv_obj_set_x(ui_PasswordTx, 0);
    lv_obj_set_y(ui_PasswordTx, 82);
    lv_obj_remove_flag(ui_PasswordTx, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_text_color(ui_PasswordTx, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PasswordTx, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PasswordTx, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PasswordTx, lv_color_hex(0x2A2A2A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PasswordTx, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PasswordTx, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_textarea_set_password_mode(ui_PasswordTx, true);

    ui_RegisterOpera = lv_obj_create(ui_UserLogin);
    lv_obj_set_width(ui_RegisterOpera, 400);
    lv_obj_set_height(ui_RegisterOpera, 430);
    lv_obj_set_x(ui_RegisterOpera, 0);
    lv_obj_set_y(ui_RegisterOpera, -10);
    lv_obj_set_align(ui_RegisterOpera, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_RegisterOpera, LV_OBJ_FLAG_HIDDEN);        /// Flags
    lv_obj_remove_flag(ui_RegisterOpera, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_RegisterOpera, lv_color_hex(0x1A1A1A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RegisterOpera, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_RegisterOpera, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Logo6 = lv_obj_create(ui_RegisterOpera);
    lv_obj_remove_style_all(ui_Logo6);
    lv_obj_set_width(ui_Logo6, 70);
    lv_obj_set_height(ui_Logo6, 70);
    lv_obj_set_align(ui_Logo6, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_Logo6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_Logo6, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Logo6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Admin2);
    ui_object_set_themeable_style_property(ui_Logo6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Admin2);
    lv_obj_set_style_bg_grad_color(ui_Logo6, lv_color_hex(0x00ECC8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Logo6, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Lightning6 = lv_image_create(ui_Logo6);
    lv_image_set_src(ui_Lightning6, &ui_img_lightning_png);
    lv_obj_set_width(ui_Lightning6, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Lightning6, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_Lightning6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Lightning6, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Lightning6, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_RegisterSelect = lv_obj_create(ui_RegisterOpera);
    lv_obj_set_width(ui_RegisterSelect, 300);
    lv_obj_set_height(ui_RegisterSelect, 30);
    lv_obj_set_x(ui_RegisterSelect, 0);
    lv_obj_set_y(ui_RegisterSelect, 80);
    lv_obj_set_align(ui_RegisterSelect, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_RegisterSelect, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_RegisterSelect, lv_color_hex(0x2A2A2A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RegisterSelect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_RegisterSelect, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Register1 = lv_obj_create(ui_RegisterSelect);
    lv_obj_set_width(ui_Register1, 100);
    lv_obj_set_height(ui_Register1, 30);
    lv_obj_set_align(ui_Register1, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_Register1, LV_OBJ_FLAG_EVENT_BUBBLE);                           /// Flags
    lv_obj_remove_flag(ui_Register1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_Register1, lv_color_hex(0x1A1A1A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Register1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Register1, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Register1, lv_color_hex(0x1A1A1A), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Register1, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_Register1, lv_color_hex(0x1A1A1A), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_opa(ui_Register1, 255, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_color(ui_Register1, lv_color_hex(0x1A1A1A), LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_bg_opa(ui_Register1, 0, LV_PART_MAIN | LV_STATE_USER_2);

    ui_Login1 = lv_obj_create(ui_RegisterSelect);
    lv_obj_set_width(ui_Login1, 100);
    lv_obj_set_height(ui_Login1, 30);
    lv_obj_set_align(ui_Login1, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Login1, LV_OBJ_FLAG_EVENT_BUBBLE);                           /// Flags
    lv_obj_remove_flag(ui_Login1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_Login1, lv_color_hex(0x2A2A2A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Login1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Login1, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Login1, lv_color_hex(0x1A1A1A), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Login1, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_Login1, lv_color_hex(0x1A1A1A), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_opa(ui_Login1, 255, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_color(ui_Login1, lv_color_hex(0x1A1A1A), LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_bg_opa(ui_Login1, 0, LV_PART_MAIN | LV_STATE_USER_2);

    ui_LoginText1 = lv_label_create(ui_RegisterSelect);
    lv_obj_set_width(ui_LoginText1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_LoginText1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_LoginText1, 29);
    lv_obj_set_y(ui_LoginText1, 0);
    lv_obj_set_align(ui_LoginText1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LoginText1, "Login");
    lv_obj_set_style_text_color(ui_LoginText1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LoginText1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RegisterText1 = lv_label_create(ui_RegisterSelect);
    lv_obj_set_width(ui_RegisterText1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_RegisterText1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_RegisterText1, -17);
    lv_obj_set_y(ui_RegisterText1, 0);
    lv_obj_set_align(ui_RegisterText1, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_RegisterText1, "Register");
    lv_obj_set_style_text_color(ui_RegisterText1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RegisterText1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RegisterBtn = lv_button_create(ui_RegisterOpera);
    lv_obj_set_width(ui_RegisterBtn, 260);
    lv_obj_set_height(ui_RegisterBtn, 35);
    lv_obj_set_x(ui_RegisterBtn, 5);
    lv_obj_set_y(ui_RegisterBtn, -40);
    lv_obj_set_align(ui_RegisterBtn, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_RegisterBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_remove_flag(ui_RegisterBtn, LV_OBJ_FLAG_SCROLLABLE);   /// Flags
    lv_obj_set_style_bg_color(ui_RegisterBtn, lv_color_hex(0x00D4FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RegisterBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LoginBtnText4 = lv_label_create(ui_RegisterBtn);
    lv_obj_set_width(ui_LoginBtnText4, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_LoginBtnText4, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_LoginBtnText4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LoginBtnText4, "Register");
    lv_obj_set_style_text_font(ui_LoginBtnText4, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RegisterArea = lv_obj_create(ui_RegisterOpera);
    lv_obj_set_width(ui_RegisterArea, 290);
    lv_obj_set_height(ui_RegisterArea, 203);
    lv_obj_set_x(ui_RegisterArea, 0);
    lv_obj_set_y(ui_RegisterArea, 10);
    lv_obj_set_align(ui_RegisterArea, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_RegisterArea, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_RegisterArea, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RegisterArea, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_RegisterArea, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PhoneText2 = lv_label_create(ui_RegisterArea);
    lv_obj_set_width(ui_PhoneText2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_PhoneText2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_PhoneText2, 5);
    lv_obj_set_y(ui_PhoneText2, 0);
    lv_label_set_text(ui_PhoneText2, "Phone");
    lv_obj_set_style_text_color(ui_PhoneText2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PhoneText2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PhoneTx2 = lv_textarea_create(ui_RegisterArea);
    lv_obj_set_width(ui_PhoneTx2, 260);
    lv_obj_set_height(ui_PhoneTx2, 35);
    lv_obj_set_x(ui_PhoneTx2, 0);
    lv_obj_set_y(ui_PhoneTx2, 22);
    lv_obj_remove_flag(ui_PhoneTx2, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_text_color(ui_PhoneTx2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PhoneTx2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PhoneTx2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PhoneTx2, lv_color_hex(0x2A2A2A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PhoneTx2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PhoneTx2, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_PhoneTx2, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PhoneTx2, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_PasswordTx1 = lv_textarea_create(ui_RegisterArea);
    lv_obj_set_width(ui_PasswordTx1, 260);
    lv_obj_set_height(ui_PasswordTx1, 35);
    lv_obj_set_x(ui_PasswordTx1, 0);
    lv_obj_set_y(ui_PasswordTx1, 82);
    lv_obj_remove_flag(ui_PasswordTx1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_text_color(ui_PasswordTx1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PasswordTx1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PasswordTx1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PasswordTx1, lv_color_hex(0x2A2A2A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PasswordTx1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PasswordTx1, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_textarea_set_password_mode(ui_PasswordTx1, true);

    ui_PasswordText1 = lv_label_create(ui_RegisterArea);
    lv_obj_set_width(ui_PasswordText1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_PasswordText1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_PasswordText1, 5);
    lv_obj_set_y(ui_PasswordText1, 60);
    lv_label_set_text(ui_PasswordText1, "PassWord");
    lv_obj_set_style_text_color(ui_PasswordText1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PasswordText1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConfirmTx = lv_textarea_create(ui_RegisterArea);
    lv_obj_set_width(ui_ConfirmTx, 260);
    lv_obj_set_height(ui_ConfirmTx, 35);
    lv_obj_set_x(ui_ConfirmTx, 0);
    lv_obj_set_y(ui_ConfirmTx, 142);
    lv_obj_remove_flag(ui_ConfirmTx, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_text_color(ui_ConfirmTx, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ConfirmTx, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ConfirmTx, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ConfirmTx, lv_color_hex(0x2A2A2A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ConfirmTx, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ConfirmTx, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_textarea_set_password_mode(ui_ConfirmTx, true);

    ui_ConfirmText = lv_label_create(ui_RegisterArea);
    lv_obj_set_width(ui_ConfirmText, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_ConfirmText, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_ConfirmText, 5);
    lv_obj_set_y(ui_ConfirmText, 120);
    lv_label_set_text(ui_ConfirmText, "Confirm Password");
    lv_obj_set_style_text_color(ui_ConfirmText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ConfirmText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard1 = lv_keyboard_create(ui_UserLogin);
    lv_obj_set_width(ui_Keyboard1, 400);
    lv_obj_set_height(ui_Keyboard1, 140);
    lv_obj_set_x(ui_Keyboard1, 0);
    lv_obj_set_y(ui_Keyboard1, 15);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN); /// Flags
    lv_obj_set_style_radius(ui_Keyboard1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Keyboard1, lv_color_hex(0x1A1A1A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Keyboard1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Keyboard1, lv_color_hex(0x2A2A2A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Keyboard1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Keyboard1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Keyboard1, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Keyboard1, lv_color_hex(0x1A1A1A), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_opa(ui_Keyboard1, 255, LV_PART_MAIN | LV_STATE_USER_1);

    lv_obj_set_style_bg_color(ui_Keyboard1, lv_color_hex(0x2A2A2A), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Keyboard1, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Keyboard1, lv_color_hex(0xCCCCCC), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Keyboard1, lv_color_hex(0xE0E0E0), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Keyboard1, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Keyboard1, lv_color_hex(0x2A2A2A), LV_PART_ITEMS | LV_STATE_USER_1);
    lv_obj_set_style_bg_opa(ui_Keyboard1, 255, LV_PART_ITEMS | LV_STATE_USER_1);

    lv_obj_add_event_cb(ui_BackIndex, ui_event_BackIndex, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Register, ui_event_Register, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LoginBtn, ui_event_LoginBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PhoneTx1, ui_event_PhoneTx1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PasswordTx, ui_event_PasswordTx, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Login1, ui_event_Login1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RegisterBtn, ui_event_RegisterBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PhoneTx2, ui_event_PhoneTx2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PasswordTx1, ui_event_PasswordTx1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ConfirmTx, ui_event_ConfirmTx, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboard1, ui_PhoneTx1);
}

void ui_Screen2_screen_destroy(void)
{
    if (ui_Screen2)
        lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_UserLoginSlider = NULL;
    ui_BackIndex = NULL;
    ui_BackIndexText = NULL;
    ui_UserLogo1 = NULL;
    ui_LogoImage2 = NULL;
    ui_UserText2 = NULL;
    ui_UserInfo2 = NULL;
    ui_Info13 = NULL;
    ui_Info9 = NULL;
    ui_Info10 = NULL;
    ui_Info11 = NULL;
    ui_Image13 = NULL;
    ui_Image8 = NULL;
    ui_Image10 = NULL;
    ui_Image11 = NULL;
    ui_Image12 = NULL;
    ui_UserLogin = NULL;
    ui_LoginOpera = NULL;
    ui_Logo2 = NULL;
    ui_Lightning2 = NULL;
    ui_LoginSelect = NULL;
    ui_Login = NULL;
    ui_Register = NULL;
    ui_LoginText = NULL;
    ui_RegisterText = NULL;
    ui_LoginBtn = NULL;
    ui_LoginBtnText = NULL;
    ui_LoginArea = NULL;
    ui_PhoneText1 = NULL;
    ui_PhoneTx1 = NULL;
    ui_PasswordText = NULL;
    ui_PasswordTx = NULL;
    ui_RegisterOpera = NULL;
    ui_Logo6 = NULL;
    ui_Lightning6 = NULL;
    ui_RegisterSelect = NULL;
    ui_Register1 = NULL;
    ui_Login1 = NULL;
    ui_LoginText1 = NULL;
    ui_RegisterText1 = NULL;
    ui_RegisterBtn = NULL;
    ui_LoginBtnText4 = NULL;
    ui_RegisterArea = NULL;
    ui_PhoneText2 = NULL;
    ui_PhoneTx2 = NULL;
    ui_PasswordTx1 = NULL;
    ui_PasswordText1 = NULL;
    ui_ConfirmTx = NULL;
    ui_ConfirmText = NULL;
    ui_Keyboard1 = NULL;
}
