// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_IndexTop;
extern lv_obj_t * ui_Logo;
extern lv_obj_t * ui_Lightning;
extern lv_obj_t * ui_functions;
extern lv_obj_t * ui_clock;
extern lv_obj_t * ui_ClockIcon;
extern lv_obj_t * ui_ClockText;
extern lv_obj_t * ui_location;
extern lv_obj_t * ui_ClockIcon1;
extern lv_obj_t * ui_IntellText;
extern lv_obj_t * ui_car;
extern lv_obj_t * ui_ClockIcon2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_IndexText;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_IndexBottom;
extern lv_obj_t * ui_UserAndAdmin;
extern void ui_event_Admin(lv_event_t * e);
extern lv_obj_t * ui_Admin;
extern lv_obj_t * ui_AdminLogo3;
extern lv_obj_t * ui_LogoImage6;
extern lv_obj_t * ui_AdminInfo2;
extern lv_obj_t * ui_Info21;
extern lv_obj_t * ui_Info17;
extern lv_obj_t * ui_Info18;
extern lv_obj_t * ui_Info19;
extern lv_obj_t * ui_Image23;
extern lv_obj_t * ui_Image19;
extern lv_obj_t * ui_Image20;
extern lv_obj_t * ui_Image21;
extern lv_obj_t * ui_AdminText2;
extern void ui_event_User(lv_event_t * e);
extern lv_obj_t * ui_User;
extern lv_obj_t * ui_UserLogo2;
extern lv_obj_t * ui_LogoImage4;
extern lv_obj_t * ui_UserInfo3;
extern lv_obj_t * ui_Info1;
extern lv_obj_t * ui_Info2;
extern lv_obj_t * ui_Info3;
extern lv_obj_t * ui_Info4;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_UserText3;
extern lv_obj_t * ui_BottomText;
extern lv_obj_t * ui_BText;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

