// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef _UI_THEMES_H
#define _UI_THEMES_H

#ifdef __cplusplus
extern "C" {
#endif

#define UI_THEME_COLOR_ADMIN1 0
#define UI_THEME_COLOR_ADMIN2 1
#define UI_THEME_COLOR_ADMIN3 2

#define UI_THEME_DEFAULT 0

#define UI_THEME_ADMINCOLOR 1

extern const ui_theme_variable_t _ui_theme_color_Admin1[2];
extern const ui_theme_variable_t _ui_theme_alpha_Admin1[2];

extern const ui_theme_variable_t _ui_theme_color_Admin2[2];
extern const ui_theme_variable_t _ui_theme_alpha_Admin2[2];

extern const ui_theme_variable_t _ui_theme_color_Admin3[2];
extern const ui_theme_variable_t _ui_theme_alpha_Admin3[2];

extern const uint32_t * ui_theme_colors[2];
extern const uint8_t * ui_theme_alphas[2];
extern uint8_t ui_theme_idx;

void ui_theme_set(uint8_t theme_idx);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
