// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "ui.h"


const ui_theme_variable_t _ui_theme_color_Admin1[2] = {0x3DFD84, 0x3DFD84};
const ui_theme_variable_t _ui_theme_alpha_Admin1[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_Admin2[2] = {0xBADA5D, 0xBADA5D};
const ui_theme_variable_t _ui_theme_alpha_Admin2[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_Admin3[2] = {0xF9B018, 0xF9B018};
const ui_theme_variable_t _ui_theme_alpha_Admin3[2] = {255, 255};
uint8_t ui_theme_idx = UI_THEME_DEFAULT;


void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

